<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- declare inertia and mass -->
    <!-- so the base link can call the mass and inertia -->
    <xacro:include filename="$(find fishbot_description)/urdf/fishbot/common_inertial.xacro"/>

    <xacro:macro name="base_xacro" params="length radius">
        <link name="base_footprint" />

        <link name="base_link">
        <!-- Components' appearance -->
            <visual>
                <!-- Offset and rotation along it's own geometric center -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- Geometry -->
                <geometry>
                    <!-- length is height (m) -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- Material and color -->
                <material name="white">
                    <!-- a is transparency -->
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
            
            <!-- add collision propoerty -->
            <collision>
                <!-- Offset and rotation along it's own geometric center -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- Geometry -->
                <geometry>
                    <!-- length is height (m) -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- Material and color -->
                <material name="white">
                    <!-- a is transparency -->
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </collision>

            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>

        </link>

        <!-- Let the bottom of the robot stick to the ground (the frame's origin) -->
        <!-- since the base link's center is the origin of the frame shown in rviz originally -->
        <!-- length is the base link's length -->
        <!-- 0.032 is the radius of the wheels -->
        <!-- -0.001 is to make the wheels tightly adhere to the ground -->
        <joint name="ground_joint" type="fixed">
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint"/>
            <child link="base_link"/>
        </joint>

    </xacro:macro>
    

</robot>
